version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '{asctime} - {name} - {levelname} - {message}'
    style: '{'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

root:
  level: DEBUG
  handlers: [console]
